# Generated by Django 5.0.6 on 2024-06-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_answer_modify_counter_comment_modify_counter_and_more'),
        ('pybo', '0006_auto_20200507_1449'),
    ]

    operations = [
    ]
